// <auto-generated />
using System;
using FX.FP.AuthenticationCenter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FX.FP.AuthenticationCenter.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    partial class AuthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FX.FP.AuthenticationCenter.Data.Models.APIKeyInfo", b =>
                {
                    b.Property<string>("GUID")
                        .HasColumnType("varchar(36)");

                    b.Property<string>("AllowIps")
                        .IsRequired()
                        .HasColumnType("varchar(120)");

                    b.Property<string>("AppID")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AppSecret")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("BackReason")
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("LinkMan")
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LinkPhone")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<int?>("OrderNum")
                        .HasColumnType("int");

                    b.Property<string>("PlatformName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ValidityDate")
                        .HasColumnType("datetime");

                    b.HasKey("GUID");

                    b.ToTable("T_APIKeyInfo", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
